name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
            - production
        paths:
            - 'docs/**'

jobs:
  main-or-production:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: main
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: ./.github/workflows/test-github-call.yml
          with:
            target-env: dev
        - name: production
          if: ${{ github.ref == 'refs/heads/production' }}
          uses: ./.github/workflows/test-github-call.yml
          with:
            target-env: prod
        - name: pre-production
          uses: ./.github/workflows/test-github-call.yml
          with:
            target-env: pre-production

