name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
            - production
        paths:
            - 'docs/**'

jobs:
  main-or-production:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: main
          if: ${{ github.ref == 'refs/heads/main' }}
          run: |
            echo "This environments is main"
            echo "Task is running for main"
        - name: production
          if: ${{ github.ref == 'refs/heads/production' }}
          run: |
            echo "New push to production detected. Please trigger the manual deployment workflow."

