name: Deployment Workflow
on:
  workflow_call:
    inputs:
      target_env:
        description: 'Environment to deploy'
        required: true
        type: string
      deploy_path:
        description: 'Path to deploy'
        required: true
        type: string
      directory_name:
        description: 'directory name for deploy'
        required: true
        type: string
      version:
        description: 'version'
        required: false
        type: string
    secrets:
      aws_account_id:
        required: true

env:
    REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ inputs.target_env }} environment..."
          # 環境に応じたデプロイスクリプトを実行
          if [ "${{ inputs.target_env }}" = "dev" ]; then
            echo "Deploy commands for Develop environment"
            # Develop環境向けデプロイコマンド
          elif [ "${{ inputs.target_env }}" = "pre-production" ]; then
            echo "Deploy commands for Pre-Production environment"
            # Pre-Production環境向けデプロイコマンド
          elif [ "${{ inputs.target_env }}" = "production" ]; then
            echo "Deploy commands for Production environment"
            # Production環境向けデプロイコマンド
          fi
          # 本来はこういう使い方はしない＆echoしても何も表示されない
          echo "aws account id is ${{ secrets.aws_account_id }}"
          echo "Deploy path is ${{ inputs.deploy_path }}"
          echo "The target region is ${{ env.REGION }}"
          if [ "${{ inputs.version }}" = "" ]; then
            echo "No Version"
          else
            echo ${{ inputs.version }}
          fi