name: Unified Deployment Workflow

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: 'main'
            env: 'develop'
          - branch: 'production'
            env: 'pre-production'
          - branch: 'production'
            env: 'production'

    # 実行条件を追加して、プッシュされたブランチがマトリックス定義と一致するか確認

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to ${{ matrix.env }}
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        uses: ./.github/workflows/test-github-call.yml
        with:
          target_env: ${{ matrix.env }}
          deploy_path: path_${{ matrix.env }}