name: dispatch

on:
    workflow_dispatch:
      inputs:
        target_env:
          description: 'target environments'
          required: true
          default: 'pre-production'
          type: choice
          options:
          - pre-production
          - production

jobs:
    pre-production-or-production:
        runs-on: ubuntu-latest
        steps:
        - name: pre-production
          if:  ${{ inputs.target_env == 'pre-production' }}
          run: |
            echo "This environments is pre-production"
            echo "Task is running for pre-production"
        - name: production
          if:  ${{ inputs.target_env == 'production' }}
          run: |
            echo "This environments is production"
            echo "Task is running for production"