name: Unified Deployment Workflow

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'docs/**'

jobs:
  deploy-develop:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test-github-call.yml
    with:
      target_env: 'develop'
      deploy_path: 'path_main'

  deploy-pre-production:
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/test-github-call.yml
    with:
      target_env: 'pre-production'
      deploy_path: 'path_production'

  deploy-production:
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/test-github-call.yml
    with:
      target_env: 'production'
      deploy_path: 'path_production'