name: Manual Deployment to Production
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy:'
        required: true
        type: choice
        options:
          - pre-production
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment."
          # Add your deployment commands here