name: Unified Deployment Workflow

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'docs/**'

jobs:
  set-env:
    uses: ./.github/workflows/test-github-call.yml
    strategy:
      matrix:
        include:
          - branch: 'main'
            env: 'develop'
          - branch: 'production'
            env: 'pre-production'
          - branch: 'production'
            env: 'production'
    with:
      target_env: ${{ matrix.env }}
      deploy_path: path_${{ matrix.branch }}