name: Unified Deployment Workflow

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'docs/**'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ matrix.branch }}
      env: ${{ matrix.env }}
    strategy:
      matrix:
        include:
          - branch: 'main'
            env: 'develop'
          - branch: 'production'
            env: 'pre-production'
          - branch: 'production'
            env: 'production'
    steps:
      - run: echo "test"

  deploy:
    needs: set-env
    uses: CHI-3/test-workflow/.github/workflows/test-github-call.yml@main
    with:
      target_env: ${{ needs.set-env.outputs.env }}
      deploy_path: path_${{ needs.set-env.outputs.branch }}