name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
            - production
        paths:
            - 'docs/**'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: main
          if: ${{ github.ref == 'refs/heads/main' }}
          run: |
            echo "This environments is main"
            echo "Task is running for main"
        - name: production
          if: ${{ github.ref == 'refs/heads/production' }}
          with:
            owner: ${{ github.repository_owner }}
            repo: ${{ github.event.repository.name }}
            ref: ${{ github.ref }}
            github_token: ${{ github.token }}
            workflow_file_name: test-github-dispatch.yml

