name: Manual Deployment to Production
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose the environment to deploy:'
        required: true
        type: choice
        options:
          - pre-production
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: pre-production
          if: ${{ inputs.target_env == 'pre-production' }}
          run: |
            echo "This environments is pre-production"
        - name: production
          if: ${{ inputs.target_env == 'pre-production' }}
          run: |
            echo "This environments is production"