name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
            - production
        paths:
            - 'docs/**'

jobs:
  main:
    uses: ./.github/workflows/test-github-call.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      target_env: main
    if: ${{ github.ref == 'refs/heads/production }}
    strategy:
      matrix:
        target_env: [ 'pre-production', 'production' ]
