name: Deployment Workflow
on:
  workflow_call:
    inputs:
      target_env:
        description: 'Environment to deploy'
        required: true
        type: string
      deploy_path:
        description: 'Path to deploy'
        required: true
        type: string
    secrets:
        AWS_ACCOUNT_ID_DEV:
            description: 'account id of dev environment'
            required: false
        AWS_ACCOUNT_ID_PRE_PROD:
            description: 'account id of pre_production environment'
            required: false
        AWS_ACCOUNT_ID_PROD:
            description: 'account id of production environment'
            required: false

env:
    REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ inputs.target_env }} environment..."
          # 環境に応じたデプロイスクリプトを実行
          if [ "${{ inputs.target_env }}" = "dev" ]; then
            echo "Deploy commands for Develop environment"
            echo AWS_ACCOUNT_ID=`${{ secrets.AWS_ACCOUNT_ID_DEV }}" | sed 's/./& /g'` >> $GITHUB_ENV
            # Develop環境向けデプロイコマンド
          elif [ "${{ inputs.target_env }}" = "pre-production" ]; then
            echo "Deploy commands for Pre-Production environment"
            echo AWS_ACCOUNT_ID=`${{ secrets.AWS_ACCOUNT_ID_PRE_PROD }}" | sed 's/./& /g'` >> $GITHUB_ENV
            # Pre-Production環境向けデプロイコマンド
          elif [ "${{ inputs.target_env }}" = "production" ]; then
            echo "Deploy commands for Production environment"
            echo AWS_ACCOUNT_ID=`${{ secrets.AWS_ACCOUNT_ID_PROD }}" | sed 's/./& /g'` >> $GITHUB_ENV
            # Production環境向けデプロイコマンド
          fi
          echo "account id is $AWS_ACCOUNT_ID"
          echo "Deploy path is ${{ inputs.deploy_path }}"
          echo "The target region is ${{ env.REGION }}"